language: objective-c
osx_image: xcode7
before_install:
  - gem install cocoapods
  - pod install
script:
  - xctool -workspace ShortTrips.xcworkspace -scheme ShortTrips -sdk iphonesimulator build test
