language: objective-c
osx_image: xcode7
before_install:
  - gem install cocoapods
  - pod install
script:
  - xcodebuild -alltargets -configuration Debug -sdk iphonesimulator clean SYMROOT=build OBJROOT=build/Intermediates
  - xcodebuild -workspace ShortTrips.xcworkspace -scheme ShortTrips -configuration Debug build test -destination "platform=iOS Simulator,name=iPhone 6" SYMROOT=build OBJROOT=build/Intermediates
