language: objective-c
osx_image: xcode7
before_install:
  - gem install cocoapods
  - pod install
script:
  - xcodebuild build test -workspace ShortTrips.xcworkspace -scheme 'ShortTrips' -sdk iphonesimulator9.0
