language: objective-c
osx_image: xcode6.4
before_install:
  - gem install cocoapods
  - pod install

  # copied from http://docs.travis-ci.com/user/common-build-problems/#Mac%3A-Code-Signing-Errors
  - KEY_CHAIN=ios-build.keychain
  - security create-keychain -p travis $KEY_CHAIN
  # Make the keychain the default so identities are found
  - security default-keychain -s $KEY_CHAIN
  # Unlock the keychain
  - security unlock-keychain -p travis $KEY_CHAIN
  # Set keychain locking timeout to 3600 seconds
  - security set-keychain-settings -t 3600 -u $KEY_CHAIN

script:
  - xctool -workspace ShortTrips.xcworkspace -scheme ShortTrips build test
